name: Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Run tests
        run: pnpm run test

      - name: Build app
        run: |
          export ROLLBAR_ACCESS_TOKEN_CLIENT=${{ secrets.ROLLBAR_ACCESS_TOKEN_CLIENT }}
          pnpm run build

      - name: Configure Git Credentials
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update the gh-pages branch
        run: |
          export GIT_VERSION=$(git rev-parse --short HEAD)
          rm -rf packages node_modules .gitignore index.html
          cp -r dist/* .
          git init
          git checkout -b gh-pages
          git add -A
          git commit -m "Deploy"
          git push -f origin gh-pages
          export ROLLBAR_ACCESS_TOKEN_SERVER=${{ secrets.ROLLBAR_ACCESS_TOKEN_SERVER }}
          export APP_HOST=https://wataruoguchi.github.io/poc-sourcemap/
          ./rollbar-upload-sourcemaps.mjs
